#!/bin/bash
yum update -y
yum install vim* curl* wget* unzip* nfs* -y
yum install http* --skip-broken -y
service httpd start
chkconfig httpd on

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-4463510f.efs.us-east-1.amazonaws.com:/ /var/www/html/

service httpd restart

wget https://www.free-css.com/assets/files/free-css-templates/download/page231/bizexpress-v1.0.1.zip
unzip *.zip
cd Biz*
mv * /var/www/html/

service httpd restart
